name: main

on:
  push:
    branches: [main]

jobs:
  start_and_test_node:
    name: Start Mangata node and test it's response
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Mangata node
        run: docker-compose up -d
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn
      - uses: ifaxity/wait-on-action
        with:
          resource: http://localhost:40399/metrics
      - run: yarn test
      - name: Stop containers
        if: always()
        run: docker-compose down