name: main

on:
  push:
    branches: [main]

jobs:
  start_and_test_node:
    name: Start Mangata node and test it's response
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Mangata node
        run: docker-compose up -d
      
      - name: Setup caching for NPM dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
  
      - name: Install dependencies
        run: yarn
     
      - name: Waiting for node metrics endpoint to become available
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:40399/metrics
      
      - name: Test node endpoint
        run: yarn test
      
      - name: Stop Mangata node
        if: always()
        run: docker-compose down